### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by eater** [ra-om/scripts#1]
Looks cool! Per the instructions [here](https://github.com/i3/i3/pull/3085#issuecomment-817326998) I installed the dependencies. I put the two executables in my path. I created `bindsym button3 exec mouse_id`. Now when I right-click a window's title and drag into another area of the screen, it toggles the mark `b` on the window, but nothing moves. (I also tried `bindsym --release button3 exec mouse_id`.)

What else do I need to do?

**Comment by ra-om** [comment]
mouse_id assumes MoveWindowsWithMouse is in your home folder, the line is "exec python3 MoveWindowsWithMouse"; I believe that's what's happening. Point python3 to the path of that file.

**Comment by eater** [comment]
Sorry, yes, I did point that to the right place as part of the installation but forgot to mention it in the ticket.

**Comment by ra-om** [comment]
run mouse_id in a terminal and post the output please

**Comment by eater** [comment]
Aha, `xinput list|grep -i mouse` comes up empty on my laptop -- I had to change it to `xinput list|grep -i trackpoint` and now it works!

**Comment by ra-om** [comment]
Glad you got it working!. There is no easy way to catch those in grep now that I think about it, because 'pointer' and maybe 'track-' are already reserved for virtual devices. It has to be the one with the manufacturer name in it.

**Comment by eater** [comment]
I'm glad I got it working too! I guess that also means I'll have to tweak the script on days I dock the laptop or plug in an external mouse. That's doable but not perfect.
